import { LinkType, TravelCardTypee } from "@/types";

export const links: LinkType[] = [
  {
    imgURL: "/assets/icons/login-user-sm.svg",
    label: "Sign in",
    id: 1,
    route: "sign-in",
    hrLine: true,
  },
  {
    imgURL: "/assets/icons/flight.svg",
    label: "Fights",
    id: 2,
    route: "/",
  },
  {
    imgURL: "/assets/icons/stays.svg",
    label: "Stays",
    id: 3,
    route: "stays",
  },
  {
    imgURL: "/assets/icons/car-rental.svg",
    label: "Car Rental",
    id: 4,
    route: "car-rental",
  },
  {
    imgURL: "/assets/icons/flight-hotel.svg",
    label: "Flight+Hotel",
    id: 5,
    route: "flight-hotel",
    hrLine: true,
  },
  {
    imgURL: "/assets/icons/explore.svg",
    label: "Explore",
    id: 6,
    route: "explore",
  },
  {
    imgURL: "/assets/icons/direct.svg",
    label: "Direct",
    id: 7,
    route: "direct",
  },
  {
    imgURL: "/assets/icons/best-time-to-travel.svg",
    label: "Best Time To Travel",
    id: 8,
    route: "best-time-to-travel",
    hrLine: true,
  },
  {
    imgURL: "/assets/icons/feedback.svg",
    label: "Feedback",
    id: 9,
    route: "feedback",
    hrLine: true,
  },
  {
    imgURL: "/assets/icons/heart-filled.svg",
    label: "Trips",
    id: 10,
    route: "trips",
    hrLine: true,
  },
  {
    imgURL: "/assets/icons/kayak-business.svg",
    label: "Kayak For Business",
    id: 11,
    route: "kayak-for-business",
    hrLine: true,
  },
  {
    imgURL: "/assets/icons/ind-flag.svg",
    label: "English",
    id: 12,
    route: "/language",
  },
  {
    imgURL: "/assets/icons/inr.svg",
    label: "Indian Rupee",
    id: 13,
    route: "currency",
  },
];

export const cardDatas: TravelCardTypee[] = [
  {
    name: "Delhi",
    id: 1,
    src: "/assets/images/img1.jpg",
    badge: "direct",
    pricing: 12932,
  },
  {
    name: "Lucknow",
    id: 2,
    src: "/assets/images/img2.jpg",
    badge: "direct",
    pricing: 23095,
  },
  {
    name: "Mumbai",
    id: 3,
    src: "/assets/images/img3.jpg",
    badge: "direct",
    pricing: 45876,
  },
  {
    name: "Bangalore",
    id: 4,
    src: "/assets/images/img4.jpg",
    badge: "direct",
    pricing: 57321,
  },
  {
    name: "Goa",
    id: 5,
    src: "/assets/images/img5.jpg",
    badge: "direct",
    pricing: 87123,
  },
  {
    name: "Varanasi",
    id: 6,
    src: "/assets/images/img6.jpg",
    badge: "direct",
    pricing: 41234,
  },
  {
    name: "Chennai",
    id: 7,
    src: "/assets/images/img7.jpg",
    badge: "direct",
    pricing: 98123,
  },
  {
    name: "Hyderabad",
    id: 8,
    src: "/assets/images/img8.jpg",
    badge: "direct",
    pricing: 54321,
  },
];
